@baseURL = https://
//@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzM4MTk0NzdjYzAxYjg5YmE1YmZjY2EiLCJlbWFpbCI6ImthbGxlQGFyY2FkYS5maSIsImlhdCI6MTY2NTM4OTE5OCwiZXhwIjoxNjY1NDc1NTk4fQ.zGTXRQ5K1gxHFloACWs43hFjGCaxMThWXOZz9YTXz3A
GET {{baseURL}}/orders/
Content-Type: application/json
//Authorization: {{token}}

###

DELETE  {{baseURL}}/orders/id?
Content-Type: application/json


###

POST {{baseURL}}/orders/
Content-Type: application/json


{
    "id": "6343d374da0e4f5d798749ee",
    "startDate": "2021-12-19",
    "endDate": "2021-12-20"
}

###

PATCH  {{baseURL}}/orders/id
Content-Type: application/json

{
    "id": "6338169a46382679a7234766"
}